---
title: "data challenge"
author: "Lucia Tan"
date: "05/02/2022"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr) 
data_20194 <- read_csv("2019Form4.csv")
data_20196 <- read_csv("2019Form6.csv")
```


```{r}
combine <- left_join(data_20194, data_20196, by = c("EMPLOYERNAME", "LOCATION", "OCCGROUP", "NAICSCLASSTITLE", "EMPLOYMENTSTATUS"))%>%
  select(EMPLOYERNAME,OCCGROUP,LOCATION,ALLWOMENCOUNT.x,ALLWOMENCOUNT.y,ABORIGALLCOUNT.x, ABORIGALLCOUNT.y,ALLCOUNT.x, ALLCOUNT.y,VISMINALLCOUNT.x, VISMINALLCOUNT.y)
```

```{r}
combine[is.na(combine)] <- 0
combine %>% 
  summarise(prop_all = sum(ALLCOUNT.y)/sum(ALLCOUNT.x),
            prop_women = sum(ALLWOMENCOUNT.y)/sum(ALLWOMENCOUNT.x),
            prop_ab = sum(ABORIGALLCOUNT.y)/sum(ABORIGALLCOUNT.x),
            prob_vis = sum(VISMINALLCOUNT.y)/sum(VISMINALLCOUNT.x))
```
```{r}
data_20194 <- data_20194 %>% select(-NAICSCLASSTITLE)
data_20194[is.na(data_20194)] <- 0
pie_data <- data_20194 %>% group_by(OCCGROUP)%>%
  filter(OCCGROUP != "Overall")%>%
  summarise(aboriginal = sum(ABORIGALLCOUNT),
            minority = sum(VISMINALLCOUNT),
            disabilities = sum(PWDALLCOUNT),
            all = sum(ALLCOUNT))
```
```{r}
pie(pie_data$minority,pie_data$OCCGROUP)
write.csv(pie_data,"pie.csv")
```

```{r}
data_20193 <- read_csv("2019Form.csv")
data_20193 <- data_20193 %>% group_by(SALARYRANGE)%>% filter(SALARYRANGE != "Overall")%>%
  select(-NAICSCLASSTITLE)
data_20193[is.na(data_20193)] <- 0

clean <- data_20193 %>% summarise(ab = sum(ABORIGALLCOUNT),
                         minority = sum(VISMINALLCOUNT),
                        disabilities = sum(PWDALLCOUNT),
                        all = sum(ALLCOUNT))

write.csv(clean,"histogram.csv")

```



